title: "Jesse Jenks"
description: "Homepage for Jesse Jenks"

author:
  name: 'Jesse Jenks'
  first_name: 'Jesse'
  last_name: 'Jenks'
  email: 'jjenks@pugetsound.edu'
  github_username: 'jessejenks'

markdown: kramdown

permalink: /blog/:year/:month/:day/:title

gems: [jekyll-paginate]
paginate: 5
paginate_path: "/blog/page:num/"
